// Code generated by goctl. DO NOT EDIT.
// Source: zero.proto

package server

import (
	"context"

	"go-zero-boilerplate/app/zero-service/api/pb"
	"go-zero-boilerplate/app/zero-service/internal/logic/identity"
	"go-zero-boilerplate/app/zero-service/internal/svc"
)

type IdentityServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedIdentityServer
}

func NewIdentityServer(svcCtx *svc.ServiceContext) *IdentityServer {
	return &IdentityServer{
		svcCtx: svcCtx,
	}
}

func (s *IdentityServer) WalletLoginNonce(ctx context.Context, in *pb.WalletLoginNonceReq) (*pb.WalletLoginNonceResp, error) {
	l := identitylogic.NewWalletLoginNonceLogic(ctx, s.svcCtx)
	return l.WalletLoginNonce(in)
}

func (s *IdentityServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := identitylogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *IdentityServer) LoginByWallet(ctx context.Context, in *pb.LoginByWalletReq) (*pb.LoginByWalletResp, error) {
	l := identitylogic.NewLoginByWalletLogic(ctx, s.svcCtx)
	return l.LoginByWallet(in)
}

func (s *IdentityServer) Userinfo(ctx context.Context, in *pb.UserinfoReq) (*pb.UserinfoResp, error) {
	l := identitylogic.NewUserinfoLogic(ctx, s.svcCtx)
	return l.Userinfo(in)
}
