// Code generated by goctl. DO NOT EDIT.
// Source: zero.proto

package server

import (
	"context"

	"go-zero-boilerplate/api/pb"
	"go-zero-boilerplate/internal/logic/health"
	"go-zero-boilerplate/internal/svc"
)

type HealthServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedHealthServer
}

func NewHealthServer(svcCtx *svc.ServiceContext) *HealthServer {
	return &HealthServer{
		svcCtx: svcCtx,
	}
}

func (s *HealthServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := healthlogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
